services:
  ecommerce-gateway:
    build:
      context: .
      dockerfile: Ecommerce.ApiGatewaySolution/Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  order-api:
    build:
      context: .
      dockerfile: Ecommerce.OrderApiSolution/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  product-api:
    build:
      context: .
      dockerfile: Ecommerce.ProductApiSolution/Dockerfile
    ports:
      - "5002:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
  
  auth-api:
    build:
      context: .
      dockerfile: Ecommerce.AuthenticationApiSolution/Dockerfile
    ports:
      - "5003:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

networks:
  default:
    driver: bridge